# Generated by Django 4.2.7 on 2023-11-20 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_place_totalhourstospend'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set(),
        ),
        migrations.AlterIndexTogether(
            name='rating',
            index_together=set(),
        ),
    ]
